name: Update Name Manifest
on:
  push:
    paths:
      - 'names/**'
      - '!names/manifest.json'

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Update manifest
        run: |
          cd names
          # Create JSON array
          echo "{" > manifest.json
          echo "  \"files\": [" >> manifest.json
          
          # List all JSON files except manifest.json
          files=$(ls *.json | grep -v manifest.json | sort)
          
          # Convert to comma-separated JSON array
          first=true
          for file in $files; do
            if [ "$first" = true ]; then
              echo "    \"$file\"" >> manifest.json
              first=false
            else
              sed -i '$ s/$/,/' manifest.json
              echo "    \"$file\"" >> manifest.json
            fi
          done
          
          echo "  ]" >> manifest.json
          echo "}" >> manifest.json
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add names/manifest.json
          git commit -m "Auto-update name manifest" || echo "No changes"
          git push